version: '3'

services:
  server:
    build: ./server
    command: npm run dev
    env_file:
      - server/.env
    ports:
      - "5000:5000"
    depends_on:
      - server_db
    restart: always

  server_db:
    image: postgres:12
    env_file:
      - server/.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
