version: '3'
services:

  nginx:
    image: nginx:1.17.10
    depends_on:
      - server
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build: ./client
    env_file:
      - client/.env
    ports:
      - "3000:80"
    restart: always

  server:
    build: ./server
    command: npm run dev
    env_file:
      - server/.env_docker
    ports:
      - "5000:5000"
    volumes:
      - ./server/static:/server/static
    depends_on:
      - server_db
    restart: always

  server_db:
    image: postgres:12
    env_file:
      - server/.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
